services:
  - type: web
    name: meeting-summarizer-backend
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: GROQ_API_KEY
        sync: false
